name: Test App With Cache

on:
  workflow_dispatch:
    inputs:
      version:
        description: "tag version"
        required: true
        default: "v0.0.1"

jobs:
  publish:
    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            use-cross: false

          # - os: ubuntu-20.04
          #   target: x86_64-unknown-linux-musl
          #   use-cross: false
          
          - os: ubuntu-20.04
            target: aarch64-unknown-linux-gnu
            use-cross: true

          # - os: ubuntu-20.04
          #   target: aarch64-unknown-linux-musl
          #   use-cross: true

          - os: macos-latest
            target: x86_64-apple-darwin
            use-cross: false

          - os: macos-latest
            target: aarch64-apple-darwin
            use-cross: false
          
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            use-cross: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        target: ${{ matrix.target }}
    
    - name: install dependencies (ubuntu only)
      if: matrix.os == 'ubuntu-20.04'
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: build-essential curl wget libssl-dev
        version: 1.1
    
    - name: rust cache restore
      uses: actions/cache/restore@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}


    - name: Build
      uses: actions-rs/cargo@v1
      with:
        use-cross: ${{ matrix.use-cross }}
        command: build
        args: --target ${{ matrix.target }} --release --locked
    
    - name: Rename files (only for Mac/Linux)
      if: matrix.target != 'x86_64-pc-windows-msvc'
      env:
        VERSION: ${{ inputs.version }}
      run: |
        mkdir output/
        mv target/${{ matrix.target }}/release/spark-ai-sdk-rs output/spark-ai-sdk-rs--${VERSION}-${{ matrix.target }}
    
    - name: Rename files (only for Windows)
      if: matrix.target == 'x86_64-pc-windows-msvc'
      env:
        VERSION: ${{ inputs.version }}
      run: |
        mkdir output/
        mv target/${{ matrix.target }}/release/spark-ai-sdk-rs.exe output/spark-ai-sdk-rs-$env:VERSION-${{ matrix.target }}.exe
    
    - name: Upload files
      # arg info: https://github.com/ncipollo/release-action#release-action
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        prerelease: true
        artifacts: "output/*"
        tag: ${{ inputs.version }}
        token: ${{ secrets.GITHUB_TOKEN }}
    
    
    - name: rust cache store
      uses: actions/cache/save@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}